### ISSUE TITLE
Missing environment variable prevents running tests

### ISSUE THREAD

**Issue by vijay-jaisankar** [mindsdb/mindsdb-status#15]
While attempting to run the tests after a fresh install of the dependencies, the following error appears: 
`OSError: Environment variable INTEGRATIONS_CONFIG is not set.`

---

What is the appropriate value of this environment variable to be set for the tests to run?

---

**Additional information**
Here is the full stack trace (symmetric cases for the other integrations):
```
ERROR: test_execute_query (integrations.test_supabase.MyTestCase)
Create new MySQL Datasource
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vijay/Desktop/projects/open-source/minds-db/mindsdb-status/integrations/test_supabase.py", line 17, in setUp
    self.incident = ins()
  File "/home/vijay/Desktop/projects/open-source/minds-db/mindsdb-status/utils/instatus.py", line 16, in __init__
    config  = get_value_from_json_env_var("INTEGRATIONS_CONFIG", 'instatus')
  File "/home/vijay/Desktop/projects/open-source/minds-db/mindsdb-status/utils/config.py", line 54, in get_value_from_json_env_var
    raise EnvironmentError(f'Environment variable {env_var_name} is not set.')
OSError: Environment variable INTEGRATIONS_CONFIG is not set.

```

**Comment by ZoranPandovski** [comment]
Hey @vijay-jaisankar this tests are mostly used for internal purpose and the environment values are not set

**Comment by vijay-jaisankar** [comment]
Hello Zoran, thanks for the reply.

Can you please point to possible contribution areas in this repo at the moment?

**Comment by vijay-jaisankar** [comment]
Sure thing, will do, thanks!

I'll close this issue and will contribute there.
